import CryptoKit
import Darwin
import Foundation
import ViewerBridge
import ViewerRendering

private struct ColorObservation: Encodable {
    let outcome: String
    var width: UInt32? = nil
    var height: UInt32? = nil
    var byteCount: UInt64? = nil
    var sourceRevision: String? = nil
    var maxOwnedError: Int? = nil
    var maxCPUError: Int? = nil
    var maxGPUError: Int? = nil
}

private struct ColorCheck: Encodable {
    let id: String
    let passed: Bool
    let status: String
    let expected: String
    let actual: ColorObservation
    let detail: String
}

private struct ColorReport: Encodable {
    let suite = "P1-COLOR-CHECKS"
    let taskID = "P1-COLOR-20261001"
    let fixtureManifestRevision = 2
    let baseFixtureCount = 26
    let acceptedFixtureCount = 7
    let rejectedFixtureCount = 19
    let passed: Bool
    let passedCount: Int
    let failedCount: Int
    let checks: [ColorCheck]
    let notRun = ["Actual drawable presentation and file-selection UI", "US, Palette and compressed color support", "ICC and physical monitor color matching"]
}

private enum CheckError: Error { case assertion(String) }

/// Safe categories only. Raw error reasons are inspected for path leakage but
/// never appear in a report, stderr, or an assertion message.
private enum ErrorCategory: String, Sendable {
    case resourceLimit, invalidArgument, unsupported, decodeFailed
    case sessionClosed, busy, invalidContract, copyFailed, renderingFailed, other

    static func classify(_ error: any Error) -> ErrorCategory {
        switch error {
        case ViewerPixelError.resourceLimit: .resourceLimit
        case ViewerPixelError.invalidArgument: .invalidArgument
        case ViewerPixelError.unsupported: .unsupported
        case ViewerPixelError.decodeFailed: .decodeFailed
        case ViewerPixelError.sessionClosed: .sessionClosed
        case ViewerPixelError.busy: .busy
        case ViewerPixelError.invalidContract: .invalidContract
        case ViewerPixelError.copyFailed: .copyFailed
        case is RenderingError: .renderingFailed
        default: .other
        }
    }

    static func reason(_ error: any Error) -> String? {
        switch error {
        case ViewerPixelError.resourceLimit(let reason), ViewerPixelError.invalidArgument(let reason),
             ViewerPixelError.unsupported(let reason), ViewerPixelError.decodeFailed(let reason),
             ViewerPixelError.invalidContract(let reason): reason
        default: nil
        }
    }
}

private struct FixtureEntry: Decodable, Sendable {
    let id: String
    let bytes: UInt64
    let sha256: String
    let rows: UInt32
    let columns: UInt32
    let rgba8: [UInt8]?
}
private struct FixtureManifest: Decodable, Sendable {
    let revision: Int
    let syntheticOnly: Bool
    let fixtures: [FixtureEntry]
    enum CodingKeys: String, CodingKey {
        case revision, fixtures
        case syntheticOnly = "synthetic_only"
    }
}
private struct FileDigest: Sendable, Equatable { let bytes: UInt64; let sha256: String }

private struct ColorFixture: Sendable {
    let id: String
    let width: UInt32
    let rgba: [UInt8]?
    let doubledLinearRow: [UInt8]?
    let tolerance: Int
    let rejection: ErrorCategory?
    var expected: String { rejection?.rawValue ?? "literal_rgba_and_descriptor" }
}

/// Expectations are independent literals, not generated by the decoder or
/// loaded as the pixel oracle from the manifest. Only these synthetic IDs can
/// be emitted by this executable.
private enum Fixtures {
    static let rgb: [UInt8] = [
        255,0,0,255, 0,255,0,255, 0,0,255,255,
        0,0,0,255, 255,255,255,255, 17,34,51,255
    ]
    static let ybr: [UInt8] = [
        254,0,0,255, 0,255,1,255, 0,0,254,255,
        0,0,0,255, 255,255,255,255, 128,128,128,255
    ]
    static let ybr422: [UInt8] = [
        254,0,0,255, 255,24,24,255, 0,0,254,255, 31,31,255,255,
        0,0,0,255, 255,255,255,255, 128,128,128,255, 64,64,64,255
    ]
    // Independent first-row literals at 2x magnification, using the already
    // normalized RGB patches. These exercise fractional channel interpolation.
    static let rgbLinearRow: [UInt8] = [
        255,0,0,255, 191,64,0,255, 64,191,0,255,
        0,191,64,255, 0,64,191,255, 0,0,255,255
    ]
    static let ybrLinearRow: [UInt8] = [
        254,0,0,255, 191,64,0,255, 64,191,1,255,
        0,191,64,255, 0,64,191,255, 0,0,254,255
    ]
    static let ybr422LinearRow: [UInt8] = [
        254,0,0,255, 254,6,6,255, 255,18,18,255, 191,18,82,255,
        64,6,197,255, 8,8,254,255, 23,23,255,255, 31,31,255,255
    ]
    static let all: [ColorFixture] = [
        accepted("sc-rgb-interleaved-le.dcm", rgb, linear: rgbLinearRow),
        accepted("sc-rgb-planar-le.dcm", rgb, linear: rgbLinearRow),
        accepted("sc-rgb-planar-implicit.dcm", rgb, linear: rgbLinearRow),
        accepted("sc-rgb-interleaved-be.dcm", rgb, linear: rgbLinearRow),
        rejected("us-rgb-interleaved.dcm"),
        accepted("sc-ybr-full-interleaved.dcm", ybr, linear: ybrLinearRow, tolerance: 1),
        accepted("sc-ybr-full-planar.dcm", ybr, linear: ybrLinearRow, tolerance: 1),
        rejected("defer-us-ybr-full-planar.dcm"),
        rejected("defer-us-ybr-full-interleaved.dcm"),
        accepted("sc-ybr-full-422.dcm", ybr422, linear: ybr422LinearRow, width: 4, tolerance: 1),
        rejected("defer-us-ybr-full-422.dcm", width: 4),
        rejected("sc-palette16-le.dcm"),
        rejected("sc-palette16-be.dcm"),
        rejected("us-palette16.dcm"),
        rejected("reject-rgb-planar2.dcm"),
        rejected("reject-rgb-short.dcm", category: .decodeFailed),
        rejected("reject-rgb-extra.dcm", category: .decodeFailed),
        rejected("reject-rgb-signed.dcm"),
        rejected("reject-rgb-rescale.dcm"),
        rejected("reject-422-planar1.dcm", width: 4),
        rejected("reject-422-short.dcm", width: 4, category: .decodeFailed),
        rejected("defer-422-odd-width.dcm"),
        rejected("reject-palette-short.dcm"),
        rejected("reject-palette-descriptor.dcm"),
        rejected("defer-palette8.dcm"),
        rejected("defer-palette-segmented.dcm")
    ]
    private static func accepted(_ id: String, _ rgba: [UInt8], linear: [UInt8], width: UInt32 = 3, tolerance: Int = 0) -> ColorFixture {
        ColorFixture(id: id, width: width, rgba: rgba, doubledLinearRow: linear, tolerance: tolerance, rejection: nil)
    }
    private static func rejected(_ id: String, width: UInt32 = 3, category: ErrorCategory = .unsupported) -> ColorFixture {
        ColorFixture(id: id, width: width, rgba: nil, doubledLinearRow: nil, tolerance: 0, rejection: category)
    }
}

@main
@MainActor
struct ViewerColorChecks {
    static func main() async {
        let args = Array(CommandLine.arguments.dropFirst())
        guard args.count == 1 || args.count == 2 else {
            FileHandle.standardError.write(Data("{\"status\":\"invalid_arguments\"}\n".utf8))
            exit(2)
        }
        let runner = ColorRunner(directory: args[0])
        await runner.run()
        let report = ColorReport(
            passed: runner.results.allSatisfy(\.passed), passedCount: runner.results.filter(\.passed).count,
            failedCount: runner.results.filter { !$0.passed }.count, checks: runner.results
        )
        do {
            let encoder = JSONEncoder(); encoder.outputFormatting = [.sortedKeys]
            let data = try encoder.encode(report)
            if args.count == 2 {
                let destination = URL(fileURLWithPath: args[1])
                try await Task.detached { try data.write(to: destination, options: .atomic) }.value
            }
            FileHandle.standardOutput.write(data)
            FileHandle.standardOutput.write(Data([10]))
        } catch {
            FileHandle.standardError.write(Data("{\"status\":\"report_write_failed\"}\n".utf8))
            exit(2)
        }
        if !report.passed { exit(1) }
    }
}

@MainActor
private final class ColorRunner {
    private let directory: String
    private let mainThreadCaller: Bool
    private var entries: [String: FixtureEntry] = [:]
    private var renderer: MetalFrameRenderer?
    private(set) var results: [ColorCheck] = []

    init(directory: String) {
        self.directory = URL(fileURLWithPath: directory).standardizedFileURL.path
        mainThreadCaller = Thread.isMainThread
    }
    private func path(_ id: String) -> String { URL(fileURLWithPath: directory).appendingPathComponent(id).path }
    private func require(_ condition: Bool, _ code: String) throws {
        if !condition { throw CheckError.assertion(code) }
    }

    private func check(_ id: String, expected: String, _ work: () async throws -> ColorObservation) async {
        do {
            let actual = try await work()
            results.append(ColorCheck(id: id, passed: true, status: "pass", expected: expected,
                                      actual: actual, detail: "matched"))
        } catch CheckError.assertion(let code) {
            results.append(ColorCheck(id: id, passed: false, status: "fail", expected: expected,
                                      actual: ColorObservation(outcome: "assertion"), detail: code))
        } catch {
            results.append(ColorCheck(id: id, passed: false, status: "fail", expected: expected,
                                      actual: ColorObservation(outcome: ErrorCategory.classify(error).rawValue),
                                      detail: "operation_failed"))
        }
    }

    func run() async {
        await check("fixture_inventory_and_metal", expected: "manifest2_26_and_main_actor_metal") {
            try require(mainThreadCaller, "caller_not_main_actor_main_thread")
            let manifestURL = URL(fileURLWithPath: path("manifest.json"))
            let manifest = try await Task.detached {
                try JSONDecoder().decode(FixtureManifest.self, from: Data(contentsOf: manifestURL))
            }.value
            try require(manifest.revision == 2 && manifest.syntheticOnly, "unexpected_manifest_revision_or_scope")
            let expectedIDs = Set(Fixtures.all.map(\.id))
            try require(manifest.fixtures.count == 26 && Set(manifest.fixtures.map(\.id)) == expectedIDs,
                        "manifest_fixture_inventory_differed")
            entries = Dictionary(uniqueKeysWithValues: manifest.fixtures.map { ($0.id, $0) })
            for fixture in Fixtures.all {
                let entry = entries[fixture.id]!
                try require(entry.rows == 2 && entry.columns == fixture.width, "manifest_dimensions_differed")
                if let literal = fixture.rgba {
                    try require(entry.rgba8 == literal, "manifest_disagreed_with_independent_literal")
                }
            }
            renderer = try await MetalFrameRenderer.make()
            return ColorObservation(outcome: "manifest2_26_and_main_actor_metal")
        }
        for fixture in Fixtures.all {
            await check(fixture.id, expected: fixture.expected) { try await verifyFixture(fixture) }
        }
        await check("color_expanded_payload_limits", expected: "resourceLimit_before_color_allocation") {
            try await colorLimits()
            return ColorObservation(outcome: "resourceLimit_before_color_allocation")
        }
        await check("ybr422_close_copy_gpu_last_owner", expected: "expanded32_retained_then_released") {
            try await colorOwnership()
            return ColorObservation(outcome: "expanded32_retained_then_released", width: 4, height: 2, byteCount: 32)
        }
    }

    private func digest(_ id: String) async throws -> FileDigest {
        let source = URL(fileURLWithPath: path(id))
        return try await Task.detached {
            let bytes = try Data(contentsOf: source)
            let sha = SHA256.hash(data: bytes).map { String(format: "%02x", $0) }.joined()
            return FileDigest(bytes: UInt64(bytes.count), sha256: sha)
        }.value
    }

    private func verifyFixture(_ fixture: ColorFixture) async throws -> ColorObservation {
        guard let entry = entries[fixture.id] else { throw CheckError.assertion("manifest_entry_unavailable") }
        let before = try await digest(fixture.id)
        try require(before.bytes == entry.bytes && before.sha256 == entry.sha256, "fixture_hash_or_size_differed")
        let outcome: Result<ColorObservation, any Error>
        do {
            if fixture.rgba != nil { outcome = .success(try await accepted(fixture, source: before.sha256)) }
            else { outcome = .success(try await rejected(fixture)) }
        } catch { outcome = .failure(error) }
        try require(try await digest(fixture.id) == before, "original_hash_changed")
        return try outcome.get()
    }

    private func errorHasNoPath(_ error: any Error, fixtureID: String) throws {
        if let reason = ErrorCategory.reason(error) {
            try require(!reason.contains(directory) && !reason.contains(path(fixtureID)) && !reason.contains(fixtureID),
                        "error_reason_leaked_input_path")
        }
    }

    private func resourcesReleased(_ session: ViewerPixelSession) throws {
        let snapshot = session.memorySnapshot()
        try require(snapshot.liveBytes == 0 && snapshot.cachedFrames == 0 && snapshot.activePreparations == 0,
                    "session_resources_not_released")
    }

    private func rejected(_ fixture: ColorFixture) async throws -> ColorObservation {
        let session = try ViewerPixelSession()
        do {
            _ = try await session.prepareNativeFrame(path: path(fixture.id))
            await session.close()
            throw CheckError.assertion("unsupported_or_damaged_color_accepted")
        } catch CheckError.assertion(let code) { throw CheckError.assertion(code) }
        catch {
            let category = ErrorCategory.classify(error)
            await session.close()
            try errorHasNoPath(error, fixtureID: fixture.id)
            try resourcesReleased(session)
            try require(category == fixture.rejection, "structured_error_category_differed_" + category.rawValue)
            return ColorObservation(outcome: category.rawValue)
        }
    }

    private func maxError(_ actual: [UInt8], _ expected: [UInt8], tolerance: Int) throws -> Int {
        try require(actual.count == expected.count, "rgba_length_differed")
        var maximum = 0
        for index in expected.indices {
            let difference = abs(Int(actual[index]) - Int(expected[index]))
            try require(index % 4 != 3 || actual[index] == 255, "alpha_was_not_opaque")
            maximum = max(maximum, difference)
        }
        try require(maximum <= tolerance, "rgba_channel_exceeded_tolerance")
        return maximum
    }

    private func ownedError(_ owned: OwnedPixelFrame, literal: [UInt8], tolerance: Int) throws -> Int {
        // A bounded test-only copy (24 or 32 bytes), independent of production
        // owner accounting. The borrowed pointer itself never escapes.
        try owned.withUnsafePixelBytes { bytes in try maxError(Array(bytes), literal, tolerance: tolerance) }
    }

    private func accepted(_ fixture: ColorFixture, source: String) async throws -> ColorObservation {
        guard let literal = fixture.rgba, let renderer else { throw CheckError.assertion("metal_or_literal_unavailable") }
        let session = try ViewerPixelSession(), budget = PixelCopyBudget(maxLiveBytes: UInt64(literal.count))
        let observation: ColorObservation
        do { observation = try await acceptedPayload(fixture, source: source, session: session, budget: budget, renderer: renderer) }
        catch { await session.close(); throw error }
        await session.close()
        for _ in 0..<100 {
            if session.memorySnapshot().liveBytes == 0 && budget.snapshot().liveBytes == 0 { break }
            try await Task.sleep(for: .milliseconds(10))
        }
        try resourcesReleased(session)
        try require(budget.snapshot().liveBytes == 0 && budget.snapshot().liveCopies == 0, "color_swift_owner_not_released")
        return observation
    }

    private func acceptedPayload(_ fixture: ColorFixture, source: String, session: ViewerPixelSession,
                                 budget: PixelCopyBudget, renderer: MetalFrameRenderer) async throws -> ColorObservation {
        let literal = fixture.rgba!
        let prepared = try await session.prepareNativeFrame(path: path(fixture.id))
        let info = prepared.info, display = prepared.display
        try require(info.width == fixture.width && info.height == 2 && info.rowStrideBytes == UInt64(fixture.width) * 4
                    && info.byteLen == UInt64(literal.count) && info.maskLen == 0 && info.pixelFormat == .rgba8
                    && info.valueDomain == .displayColor && info.contractRevision == 1 && info.payloadRevision == 1,
                    "rgba_payload_contract_differed")
        try require(display.descriptorRevision == 1 && display.frameIndex == 0 && display.sourceRevision == source
                    && display.windows.isEmpty && display.defaultWindow == nil && !display.canWindow
                    && !display.automaticWindow && !display.inverted && display.unit == "unknown"
                    && display.diagnostics.contains("unprofiled_rgb"), "color_display_descriptor_differed")
        let owned = try await prepared.copy(using: budget)
        try require(owned.display.sourceRevision == source && owned.info.byteLen == info.byteLen
                    && owned.withUnsafeMaskBytes { $0 == nil }, "color_copy_metadata_or_mask_differed")
        try require(budget.snapshot().liveBytes == UInt64(literal.count) && budget.snapshot().liveCopies == 1,
                    "color_copy_budget_differed")
        let copyError = try ownedError(owned, literal: literal, tolerance: fixture.tolerance)
        let uploaded = try await renderer.upload(owned)
        let nearestBaseline = try await renderer.renderOffscreen(uploaded, interpolation: .nearest)
        let linearBaseline = try await renderer.renderOffscreen(uploaded, interpolation: .linear)
        var cpuError = 0, gpuError = 0
        let windows: [VoiWindow?] = [nil, VoiWindow(center: 0, width: 1, function: .linear),
                                   VoiWindow(center: 1234, width: 987, function: .sigmoid)]
        for window in windows {
            for inverted in [false, true] {
                let cpu = try await prepared.referenceRGBA(window: window, userInvert: inverted)
                cpuError = max(cpuError, try maxError(cpu, literal, tolerance: fixture.tolerance))
                // CPU reference must preserve these already-normalized owned bytes exactly.
                _ = try owned.withUnsafePixelBytes { try maxError(Array($0), cpu, tolerance: 0) }
                for interpolation in [PixelInterpolation.nearest, .linear] {
                    let gpu = try await renderer.renderOffscreen(uploaded, window: window, userInvert: inverted,
                                                                 interpolation: interpolation)
                    gpuError = max(gpuError, try maxError(gpu, literal, tolerance: fixture.tolerance))
                    _ = try maxError(gpu, cpu, tolerance: 1)
                    let baseline = interpolation == .nearest ? nearestBaseline : linearBaseline
                    _ = try maxError(gpu, baseline, tolerance: 0)
                }
            }
        }
        let doubled = try await renderer.renderOffscreen(uploaded, interpolation: .linear,
                                                         outputWidth: Int(info.width) * 2, outputHeight: 4)
        let expectedRow = fixture.doubledLinearRow!
        // Hardware UNORM half ties may differ by one; native-grid RGB above is exact.
        _ = try maxError(Array(doubled.prefix(expectedRow.count)), expectedRow, tolerance: 1)
        return ColorObservation(outcome: "literal_rgba_and_descriptor", width: info.width, height: info.height,
                                byteCount: info.byteLen, sourceRevision: source, maxOwnedError: copyError,
                                maxCPUError: cpuError, maxGPUError: gpuError)
    }

    private func colorLimits() async throws {
        // A 422 source has 16 stored bytes and expands to 32 RGBA bytes. Limits
        // must charge the expanded destination, not nominal/stored sample bytes.
        for (id, bytes): (String, UInt64) in [("sc-rgb-planar-le.dcm", 24), ("sc-ybr-full-422.dcm", 32)] {
            let limited = try ViewerPixelSession(maxLiveBytes: 64, maxFrameBytes: bytes - 1)
            do {
                _ = try await limited.prepareNativeFrame(path: path(id))
                await limited.close(); throw CheckError.assertion("color_frame_limit_accepted")
            } catch CheckError.assertion(let code) { throw CheckError.assertion(code) }
            catch {
                await limited.close()
                try errorHasNoPath(error, fixtureID: id)
                try require(ErrorCategory.classify(error) == .resourceLimit, "color_frame_limit_wrong_error")
                try resourcesReleased(limited)
                try require(limited.memorySnapshot().peakBytes == 0, "denied_color_payload_was_reserved")
            }
            let session = try ViewerPixelSession(maxLiveBytes: bytes, maxFrameBytes: bytes)
            do {
                let prepared = try await session.prepareNativeFrame(path: path(id))
                let small = PixelCopyBudget(maxLiveBytes: bytes - 1)
                do { _ = try await prepared.copy(using: small); throw CheckError.assertion("color_copy_limit_accepted") }
                catch ViewerPixelError.resourceLimit {}
                try require(small.snapshot().liveBytes == 0 && small.snapshot().peakBytes == 0
                            && small.snapshot().liveCopies == 0, "denied_color_copy_was_reserved")
                await session.close()
            } catch { await session.close(); throw error }
            try resourcesReleased(session)
        }
    }

    private func colorOwnership() async throws {
        guard let renderer else { throw CheckError.assertion("metal_unavailable") }
        let session = try ViewerPixelSession(maxLiveBytes: 32, maxFrameBytes: 32)
        let budget = PixelCopyBudget(maxLiveBytes: 32)
        do {
            var prepared: PreparedPixelFrame? = try await session.prepareNativeFrame(path: path("sc-ybr-full-422.dcm"))
            weak let weakPrepared = prepared
            try require(await session.evictAll() == 1, "color_cache_eviction_count_differed")
            await session.close()
            try require(session.memorySnapshot().liveBytes == 32 && session.memorySnapshot().cachedFrames == 0,
                        "closed_color_handle_lost_expanded_payload")
            var owned: OwnedPixelFrame? = try await prepared!.copy(using: budget)
            weak let weakOwned = owned
            _ = try ownedError(owned!, literal: Fixtures.ybr422, tolerance: 1)
            _ = try maxError(try await prepared!.referenceRGBA(userInvert: true), Fixtures.ybr422, tolerance: 1)
            var uploaded: UploadedPixelFrame? = try await renderer.upload(owned!)
            prepared = nil
            for _ in 0..<100 {
                if weakPrepared == nil && session.memorySnapshot().liveBytes == 0 { break }
                try await Task.sleep(for: .milliseconds(10))
            }
            try require(weakPrepared == nil, "last_color_handle_still_retained")
            try resourcesReleased(session)
            owned = nil
            try require(weakOwned != nil && budget.snapshot().liveBytes == 32, "gpu_color_owner_lost_copy_charge")
            for interpolation in [PixelInterpolation.nearest, .linear] {
                _ = try maxError(try await renderer.renderOffscreen(uploaded!, userInvert: true,
                                                                  interpolation: interpolation), Fixtures.ybr422, tolerance: 1)
            }
            try require(budget.snapshot().liveBytes == 32 && budget.snapshot().liveCopies == 1,
                        "completed_gpu_color_owner_not_charged")
            uploaded = nil
            for _ in 0..<100 {
                if weakOwned == nil && budget.snapshot().liveBytes == 0 { break }
                try await Task.sleep(for: .milliseconds(10))
            }
            try require(weakOwned == nil && budget.snapshot().liveBytes == 0 && budget.snapshot().liveCopies == 0
                        && budget.snapshot().peakBytes == 32, "last_color_gpu_owner_not_released")
        } catch { await session.close(); throw error }
    }
}
